### ISSUE TITLE
Bug: getByRole('paragraph') doesn't work

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pleasantest#320]
```js
test(
  'getByRole("paragraph")',
  withBrowser.headed(async ({ utils, screen }) => {
    await utils.injectHTML(`<p>This is a paragraph</p>`);
    // throws
    const paragraph = await screen.getByRole('paragraph');
  })
);
```

The `paragraph` role is added automatically to the element by the browser. It shows up in the accessibility tree in Chrome DevTools. But the above fails.

<img width="1155" alt="Screen Shot 2021-12-01 at 5 35 39 PM" src="https://user-images.githubusercontent.com/459757/144341719-6bda05f7-250b-4cd6-995b-a0655e79d4f8.png">

**Comment by gerardo-rodriguez** [comment]
@calebeby I'm not sure where or why this fails. Is there an obvious place to look? 🤔

**Comment by calebeby** [comment]
I think this role was added in the latest aria spec which isn't widely supported by tooling/browsers yet. I could be misremembering though, I will look into it

**Comment by calebeby** [comment]
In the current published version of the spec the `paragraph` role doesn't exist, and the `<p>` tag has no implicit roles:
https://www.w3.org/TR/html-aria/#el-p, https://www.w3.org/TR/wai-aria-1.1/

In the editor's draft, the `paragraph` role exists: https://w3c.github.io/aria/#paragraph

**Comment by calebeby** [comment]
I think once it comes into the published version, then dom testing library will support it and then we can too.

**Comment by calebeby** [comment]
Oh now I am noticing that aria 1.1 is not the latest version, aria 1.2 is the latest published version. 1.2 lists the paragraph role: https://www.w3.org/TR/wai-aria-1.2/#paragraph. It shows `<p>` as a "related concept" which I don't know if that means it is applied automatically. The HTML-aria spec still says `<p>` has no implicit role: https://www.w3.org/TR/html-aria/#el-p

**Comment by calebeby** [comment]
Update: Now the html-aria spec shows p having an implicit role of `paragraph`: https://www.w3.org/TR/html-aria/#el-p

We now just have to wait for aria-query to release the new version that includes the pulled-in changes from the new spec. They already have the updates in their repo, just not published on npm: https://github.com/A11yance/aria-query/blob/2d04e2928ed8f1f99950fa5f0075f1f67bfed9c7/__tests__/src/elementRoleMap-test.js#L88
