### ISSUE TITLE
Should HTML comments be included in accessibility tree?

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pleasantest#411]
I have an HTML comment in the `<body>` like so:
```html
<body>
  <!--
    This is a comment with helpful information for developers
  -->
</body>
```
Unexpectedly, that shows up in the accessibility tree shapshot:
```
  text "This is a comment with helpful information for developers"
```

As far as I can tell, I don't see the accessibility tree in Chrome or FF showing HTML comments. Is this a bug? Or should Pleasantest be configurable to ignore HTML comments? 🤔

**Comment by calebeby** [comment]
Yep that is a bug. I think it is a bug on our end, not on dom-accessibility-api's end.

**Comment by calebeby** [comment]
Labelling this as minor - In the changelog I'll write "potentially breaking bugfix"
