### ISSUE TITLE
Idea: expect(getAccessibilityTree(page)).toMatchInlineSnapshot()

### ISSUE THREAD

**Issue by calebeby** [cloudfour/pleasantest#51]
It would be cool to write snapshot tests against the accessibility tree, something like:

```js
test(
  'asdf',
  withBrowser(async ({ utils }) => {
    // ...
    expect(await getAccessibilityTree(pageOrNode)).toMatchInlineSnapshot(`
      heading "accessible name"
        link "accessible name"
          text "asdf"
          text "asdf"
      paragraph "some text in a paragraph"
        text "some text in a paragraph"
    `)
  }),
)
```

The tree would be as similar as possible to the accessibility tree shown in Chrome/Firefox

**Comment by calebeby** [comment]
I looked into how viable this is. I couldn't find a library that would generate the tree directly, but I did find libraries that would handle parts of this: finding the roles of elements (implicitly or explicitly set) and finding the text associated with elements (testing-library's getByRole is based on these libraries):

- https://github.com/testing-library/dom-testing-library/blob/v7.30.4/src/role-helpers.js#L65
- https://github.com/A11yance/aria-query
- https://github.com/eps1lon/dom-accessibility-api

**Comment by calebeby** [comment]
Example with tab order:

```js
test(
  'asdf',
  withBrowser(async ({ utils }) => {
    // ...
    expect(await getAccessibilityTree(node)).toMatchInlineSnapshot(`
      form  (tab: 1)
        label "Email address"
          text "Email address"
        textbox "Email address" (tab: 2)
          text "It's safe with us. We hate spam!"
        label "Password"
          text "Password"
        textbox "Password" (tab: 3)
        checkbox "I accept the terms and conditions" (tab: 4)
          link "terms and conditions"
        button "Submit" (tab: 5)
          text "Submit"
    `)
  }),
)
```

I noticed there are some differences in how the tree is structured (and the names of the roles) between Chrome/FF. I think we could pick and choose what makes the most sense

**Comment by calebeby** [comment]
Maybe we could make the focus/tab order thing a separate function 🤔 I don't know what makes the most sense:

```js
test(
  'asdf',
  withBrowser(async ({ utils }) => {
    // ...
    expect(await getAccessibilityTree(node)).toMatchInlineSnapshot(`
      form
      textbox "Email address"
      textbox "Password"
      checkbox "I accept the terms and conditions"
      button "Submit"
    `)
  }),
)
```

**Comment by calebeby** [comment]
Additional use cases we might want to be able to test:

- Does screen reader read all text as expected, or are some parts chunked out in unexpected ways (I remember we ran into this on client work a while ago) (i.e. if part of the text is screen-reader-only, and some of it is visible text, does it read all as expected)
- Is aria-live used correctly (I have no idea how to test this or how to make this visible to the person writing the tests, but there is probably a way to do it that I didn't think of yet)

**Comment by calebeby** [comment]
TIL that Puppeteer has a method to get the accessibility tree!
https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-class-accessibility

It is worth looking into. At this point, I'm a little skeptical that we should use it, because its structure looks like it is Blink/Chromium specific, so if we tried out puppeteer with firefox, it probably would work differently. I'm reluctant to latch onto something that is engine-specific when it is possible to implement a solution that is more generalized.

Still though, we should look into it

**Comment by calebeby** [comment]
@gerardo-rodriguez I didn't know about the voiceover rotor until today, but when I was learning about that it seems like there is a similarity between that and the list of tabbable elements that we had talked about doing:

```js
test(
  'asdf',
  withBrowser(async ({ utils }) => {
    // ...
    expect(await getTabbableElementRoles(node)).toMatchInlineSnapshot(`
      form
      textbox "Email address"
      textbox "Password"
      checkbox "I accept the terms and conditions"
      button "Submit"
    `)
  }),
)
```

I don't have a well-formed thought about this, but it might make sense to copy some of the organization from the VO rotor into this, or name the function based on that.

Also, I started thinking about maybe adding VO methods to the user API:

```js
test(
  'asdf',
  withBrowser(async ({ user }) => {
    // ...
    expect(await user.vo.getHeadings().toString()).toMatchInlineSnapshot(`
      ...	
    `)
    await user.vo.navigateNext()
    await user.vo.navigateInto()
    await user.vo.navigateOutof()
    await expect(button).toHaveVOSelection()
    await expect(user.vo.readSelected()).toMatchInlineSnapshot('greater than some menu item')
  }),
)
```

**Comment by gerardo-rodriguez** [comment]
@calebeby I like your idea!

Even at the basic level of "list all headings" or "list all articles" or "list all links" would be good. It's another lens to help us see when we could enhance the experience. For example, if all articles on the page were listed as "article, article, article" then it would give us insight to consider making that experience better. 👍

**Comment by calebeby** [comment]
Closing this as getAccessibilityTree has been implemented/published. There are some ideas in this issue that are not implemented and might be worth implementing down the road. We can come back to them as we try out getAccessibilityTree on real work and find the pain points.
