### ISSUE TITLE
When I use the `.not.toHaveFocus()` assertion, the console message seems incorrect

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pleasantest#520]
It seems the `Execptect element with focus` messaging is incorrect. Or at least it's confusing. 🤔 

I would expect that to read something like `Expected element to not have focus`

![the-same](https://user-images.githubusercontent.com/459757/176252132-fa456189-2bf3-4fc7-965d-e3a01b52c5ea.gif)

**Comment by calebeby** [comment]
@gerardo-rodriguez Thanks!

Looks like this is a jest-dom bug: https://github.com/testing-library/jest-dom/pull/447.

Once I update that dependency should be fixed!
