### ISSUE TITLE
Docs site doesn't make it clear how to access `utils`, `screen`, `user`

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/pleasantest#610]
Step 3 of the docs shows using `utils`. Step 4 uses `screen` and `user`. 

But it never shows how to access these properties. Should we update Step 2 to load these properties?

```js
withBrowser(async () => {
```

-->

```js
withBrowser(async ({utils, screen, user}) => {
```

**Comment by Paul-Hebert** [comment]
(Happy to make a PR for this if you think this is the right approach @calebeby )

**Comment by calebeby** [comment]
Sounds good! Yeah a PR would be helpful
