### ISSUE TITLE
Target size for `.click()`

### ISSUE THREAD

**Issue by calebeby** [cloudfour/pleasantest#72]
.click() should require a minimum target size (that can be overwritten by configuration).

(Idea from @gerardo-rodriguez)

**Comment by gerardo-rodriguez** [comment]
Thanks, @calebeby!

To be clear, this isn't only for _touch_ targets. It's for targets in general (even with mouse pointer inputs). 😉 

> Small targets can be difficult to click or touch. The W3C recommends a minimum target size of 44 x 44 px to ensure that users are able to activate them. They also suggest that frequently used targets be made larger. The exceptions in this rule allow a target to be smaller than 44 px if another target that does the same thing on the same page meets the requirements, if the user gets to modify the target size themselves, or if the target is included inline in text, such as a footnote link.
- https://dequeuniversity.com/resources/wcag2.1/2.5.5-target-size

> The intent of this success criterion is to ensure that target sizes are large enough for users to easily activate them, even if the user is accessing content on a small handheld touch screen device, has limited dexterity, or has trouble activating small targets for other reasons. For instance, mice and similar pointing devices can be hard to use for these users, and a larger target will help them activate the target. 
- https://www.w3.org/WAI/WCAG21/Understanding/target-size.html

**Comment by calebeby** [comment]
@gerardo-rodriguez is this something you'd want to tackle or pair on?

**Comment by gerardo-rodriguez** [comment]
> @gerardo-rodriguez is this something you'd want to tackle or pair on?

@calebeby Yes, I'm interested in pairing! Maybe next week we can set time aside to work on this?

**Comment by calebeby** [comment]
Yes for sure! I am starting school on Wednesday and I will likely have some interruptions on Tuesday so I'm not sure what my work schedule will be. I'll let you know closer to then
